### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by lucy-sees** [zhorabay/To-Do-list#8]
Hi @zhorabay ,
Your project is looking great

To Highlight
✔️ Descriptive commit messages
✔️ Professional** looking README file
✔️ Good overall design
✔️ Good use of GitHub flows 👍

JavaScript Best Practices
✔️ The code adheres to JavaScript best practices for the most part. 👍
✔️ Import statements are concise and well-organized.
✔️ The variable names are descriptive.
✔️ Event listeners are appropriately placed and linked to the relevant methods
✔️ There is proper indentation and consistent formatting.

Suggestion
- Kindly add more JS modules for your code. This allows your code to be more neat and organized🙏🏾
- Kindly try to have more descriptive project file names as this helps the code viewers understand the code better and saves time while going through the project.

**Comment by zhorabay** [comment]
Thank you so much!
